version: "3.3"

networks:
  htmlcoind_testnet_network:
volumes:
  htmlcoind_testnet_volume:

services:
  janus_testnet:
    image: htmlcoin/janus:dev
    container_name: janus_testchain
    build: 
        context: ../../
        cache_from:
          - golang:1.18-alpine
    ports:
        - "24889:24889"
    environment: 
        - HTMLCOIN_RPC=http://htmlcoin:testpasswd@htmlcoin_testnet:4889
        - COMPOSE_PROJECT_NAME=testnet
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/denuoweb/janus/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - htmlcoin_testnet
    command: --bind 0.0.0.0 --port 24889 --ignoreTransactions --accounts $GOPATH/github.com/denuoweb/janus/myaccounts.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - htmlcoind_testnet_network

  htmlcoin_testnet:
    ports:
      - "4889:4889"
    image: htmlcoin/htmlcoin
    container_name: htmlcoin_testnet
    command: htmlcoind -testnet -txindex -addrindex=1 -rpcbind=0.0.0.0:4889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=htmlcoin -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
    volumes:
      - htmlcoind_testnet_volume:/root/.htmlcoin
    networks:
      - htmlcoind_testnet_network
